<script lang="ts">
	import LegalPage from '$lib/components/LegalPage.svelte';
	import type { PageProps } from './$types';
	let { data }: PageProps = $props();
	const legal = $derived(data.auth.legal);
</script>

<LegalPage title="Privacy Policy" ready={data.auth.legalReady}>
	<h2>1. Who is responsible</h2>
	<p>{legal.entity || '[legal operator name]'}, at {legal.address || '[business address]'}, in {legal.jurisdiction || '[country and state/province]'}, operates FinSight and is responsible for the personal information described here. For privacy questions or requests, contact {legal.email || '[public privacy email]'}. This policy describes the current FinSight service.</p>
	<h2>2. Information we process</h2>
	<ul>
		<li><strong>Account information:</strong> your email address, normalized username, account identifier, creation time, and the version and time of Terms acceptance.</li>
		<li><strong>Authentication information:</strong> credentials submitted when signing in, creating an account or resetting a password; session tokens, confirmation and recovery events, and authentication security records. Supabase Auth handles password storage and verification. FinSight does not copy passwords into application database tables.</li>
		<li><strong>Device and request information:</strong> hosting and authentication providers may process IP addresses, browser information, request times and security or diagnostic logs to deliver and protect the service.</li>
		<li><strong>Support communications:</strong> information you choose to send when requesting help or exercising privacy rights. Do not send passwords, recovery links or unnecessary financial details.</li>
	</ul>
	<h2>3. Financial information stays on your device</h2>
	<p>Financial values, goals, debts and allowances entered into the current planner are calculated in your browser. If you choose local saving, the profile is encrypted on your device using your separate local passcode. This feature does not upload that profile to your FinSight account. Demonstration subscription choices and usage counts also use local browser storage. Anyone with access to your unlocked browser may see information currently displayed. Account sign-out does not clear local data. You can clear the saved profile through Local Profile and remove remaining local storage through your browser settings.</p>
	<h2>4. Purposes and legal bases</h2>
	<p>We collect account information electronically through forms you submit, authentication requests and essential cookies; support information comes from your communications. For processing subject to Türkiye’s Personal Data Protection Law No. 6698 (KVKK), we rely, as applicable, on Article 5(2) conditions concerning contract performance, legal obligations, establishing or protecting rights, and legitimate interests that do not override your fundamental rights. Any processing that requires separate explicit consent will be presented separately.</p>
	<p>We use account and authentication information to create and operate accounts, sign users in and provide recovery. Where a legal basis is required, this processing is necessary to perform our agreement with you or take requested steps before entering it. We process proportionate security records to protect accounts, prevent abuse and maintain service reliability based on legitimate interests, balanced against your rights. We process support requests to provide requested assistance and meet legal obligations where applicable. Terms acceptance records help document our agreement. We process information required by valid legal obligations on that basis. We do not treat accepting the Terms as blanket consent for unrelated data uses.</p>
	<h2>5. Providers and disclosures</h2>
	<p>Supabase provides authentication and account database services. Our configured hosting and transactional email providers process information necessary to host the app and deliver account messages. These providers receive only information needed for their functions, subject to applicable arrangements. We may disclose information when legally required, to protect rights or service security, or in a business transfer with appropriate protections and notice where required. The current app includes no advertising trackers or analytics SDKs and does not sell personal information or share it for cross-context behavioral advertising.</p>
	<h2>6. Cookies and browser storage</h2>
	<p>Essential session cookies keep you signed in; they are sent to the FinSight server and are not available to application JavaScript. Their lifetime follows the authentication session configuration, and they may refresh as you use the service. Local browser storage supports the optional encrypted financial profile and demonstration settings described above. Disabling or clearing cookies signs you out or prevents authentication from working. Clearing local storage removes saved device data. No optional advertising cookies are included in the current app.</p>
	<h2>7. Retention and deletion</h2>
	<p>We retain account information while your account is active and as necessary to provide the service. You can request deletion through our contact address. We verify requests using proportionate information to protect your account. Deleting the authentication account also deletes its associated username profile. Limited information may need to be retained for a specific legal obligation, unresolved dispute or security investigation; retention depends on the applicable deadline or investigation, and access should be restricted to that purpose. Provider logs and backups follow the retention schedules identified in the published deployment details below. Local device data remains until you clear it and is unaffected by account deletion.</p>
	<h2>8. International processing and deployment details</h2>
	<p>Providers may process information outside Türkiye or your country. Transfers subject to KVKK must satisfy Article 9 and applicable implementing rules; accepting these Terms is not consent to unrestricted overseas transfers. Contact us for information about the safeguards applicable to your information.</p>
	<p>{legal.deploymentDetails || '[Before publication: identify hosting and email providers, Supabase region, processing countries, applicable transfer safeguards, log retention periods and backup deletion windows.]'}</p>
	<h2>9. Your rights</h2>
	<p>Depending on where you live and applicable law, you may request access, correction, deletion or portability of personal information, object to processing based on legitimate interests, or request restriction. Where processing relies on consent, you may withdraw it without affecting prior lawful processing. You may also complain to the relevant data protection authority. We will handle verified requests within applicable legal deadlines and explain any lawful exception. We do not make automated decisions producing legal or similarly significant effects about you; planner outputs are educational calculations for your own use.</p>
	<p>Under KVKK Article 11, you may ask whether your data is processed, request information about processing and its purposes, learn domestic and overseas recipients, request correction or deletion when conditions are met and notification of those actions to recipients, object to adverse results from exclusively automated analysis, and seek compensation for unlawful processing. Submit requests to the operator using the contact details above; applicable identity verification and statutory procedures apply. You may use the complaint mechanisms of the Turkish Personal Data Protection Authority, subject to applicable requirements.</p>
	<h2>10. Security and children</h2>
	<p>We use safeguards including authentication, access controls, encrypted connections in production and optional encrypted local profiles. No system is completely secure. Keep your device, password and local passcode secure. FinSight accounts are intended for adults aged 18 or over. If you believe a child has provided account information, contact us so we can investigate and take appropriate action.</p>
	<h2>11. Changes and contact</h2>
	<p>We will update the version date when this policy changes and notify account holders of material changes as required. We will obtain any consent required before using information for a new purpose. Contact {legal.email || '[public privacy email]'} with questions or requests.</p>
</LegalPage>
