<script lang="ts">
	import AppNavigation from '$lib/components/AppNavigation.svelte';
	let { data, form }: { data: { user: { email: string; emailVerified: boolean } | null; hasDatabase: boolean }; form?: { error?: string } } = $props();
</script>

<main class="app-shell">
	<AppNavigation user={data.user} />
	<section class="screen service-screen">
		<p class="eyebrow">Onboarding</p>
		<h2>Build your financial model</h2>
		{#if !data.hasDatabase}<div class="notice-panel">DATABASE_URL is not configured. You can view demo mode, but onboarding cannot be persisted.</div>{/if}
		{#if form?.error}<div class="notice-panel">{form.error}</div>{/if}
		<form method="POST" class="onboarding-form">
			<section class="details-panel"><div class="panel-heading"><h3>About You</h3><span class="pill tone-safe">Required</span></div><div class="two-col"><label><span>First name</span><input name="firstName" required /></label><label><span>Last name</span><input name="lastName" required /></label><label><span>Country</span><input name="country" value="US" required /></label><label><span>Preferred currency</span><select name="preferredCurrency"><option>USD</option><option>CAD</option><option>EUR</option><option>GBP</option></select></label><label><span>Employment status</span><input name="employmentStatus" /></label></div></section>
			<section class="details-panel"><div class="panel-heading"><h3>Income</h3><span class="pill tone-safe">Required</span></div><div class="two-col"><label><span>Monthly net income</span><input name="monthlyIncome" inputmode="decimal" required /></label><label><span>Income frequency</span><select name="incomeFrequency"><option>monthly</option></select></label><label><span>Additional income</span><input name="additionalIncome" inputmode="decimal" /></label><label><span>Income stability</span><select name="incomeStability"><option>stable</option><option>variable</option><option>seasonal</option><option>unpredictable</option></select></label></div></section>
			<section class="details-panel"><div class="panel-heading"><h3>Cash</h3><span class="pill tone-safe">Required</span></div><div class="two-col"><label><span>Checking balance</span><input name="checkingBalance" inputmode="decimal" required /></label><label><span>Savings balance</span><input name="savingsBalance" inputmode="decimal" required /></label><label><span>Emergency savings</span><input name="emergencySavings" inputmode="decimal" /></label></div></section>
			<section class="details-panel"><div class="panel-heading"><h3>Monthly Expenses</h3><span class="pill tone-safe">Required</span></div><div class="two-col"><label><span>Housing</span><input name="housing" inputmode="decimal" /></label><label><span>Utilities</span><input name="utilities" inputmode="decimal" /></label><label><span>Transportation</span><input name="transportation" inputmode="decimal" /></label><label><span>Food</span><input name="food" inputmode="decimal" /></label><label><span>Insurance</span><input name="insurance" inputmode="decimal" /></label><label><span>Subscriptions</span><input name="subscriptions" inputmode="decimal" /></label><label><span>Other recurring expenses</span><input name="otherExpenses" inputmode="decimal" /></label></div></section>
			<section class="details-panel"><div class="panel-heading"><h3>Debt</h3><span class="pill tone-caution">Optional</span></div><div class="two-col"><label><span>Name</span><input name="debtName" /></label><label><span>Type</span><select name="debtType"><option value="credit_card">Credit card</option><option value="auto_loan">Auto loan</option><option value="student_loan">Student loan</option><option value="other">Other</option></select></label><label><span>Current balance</span><input name="debtBalance" inputmode="decimal" /></label><label><span>APR</span><input name="debtApr" inputmode="decimal" /></label><label><span>Minimum payment</span><input name="debtMinimumPayment" inputmode="decimal" /></label><label><span>Due date</span><input name="debtDueDate" type="date" /></label></div></section>
			<section class="details-panel"><div class="panel-heading"><h3>Goals</h3><span class="pill tone-caution">Optional</span></div><div class="two-col"><label><span>Name</span><input name="goalName" /></label><label><span>Target amount</span><input name="goalTargetAmount" inputmode="decimal" /></label><label><span>Current amount</span><input name="goalCurrentAmount" inputmode="decimal" /></label><label><span>Target date</span><input name="goalTargetDate" type="date" /></label><label><span>Priority</span><select name="goalPriority"><option>medium</option><option>high</option><option>low</option></select></label><label><span>Monthly contribution</span><input name="goalMonthlyContribution" inputmode="decimal" /></label></div></section>
			<section class="details-panel"><div class="panel-heading"><h3>Financial Safety Target</h3><span class="pill tone-safe">Required</span></div><label><span>Desired emergency fund in months</span><input name="emergencyFundMonths" type="number" min="1" max="24" value="3" required /></label></section>
			<button class="primary-action" type="submit">Complete onboarding</button>
		</form>
	</section>
</main>
