<script lang="ts">
	import LegalPage from '$lib/components/LegalPage.svelte';
	import type { PageProps } from './$types';
	let { data }: PageProps = $props();
	const legal = $derived(data.auth.legal);
</script>

<LegalPage title="Terms of Service" ready={data.auth.legalReady}>
	<h2>1. Who we are and this agreement</h2>
	<p>FinSight is operated by {legal.entity || '[legal operator name]'}, at {legal.address || '[business address]'}, in {legal.jurisdiction || '[country and state/province, if applicable]'} ("we", "us"). Contact: {legal.email || '[public support email]'}. These Terms govern your use of FinSight. By creating an account and accepting these Terms, you agree to them. If you do not agree, do not create an account.</p>
	<h2>2. Eligibility and your account</h2>
	<p>You must be at least 18 and legally able to enter this agreement. Provide accurate account information, use an email address you control, and protect your password and confirmation links. Usernames are unique and case-insensitive. Do not impersonate another person, share access for unlawful purposes, or use a misleading or abusive username. Contact us promptly if you suspect unauthorized access. You are responsible for your use of the service, subject to rights and protections under applicable law.</p>
	<h2>3. Educational tools, assumptions and limitations</h2>
	<p>FinSight provides personal finance calculations, budgeting tools and hypothetical purchase comparisons for education. It does not provide investment, tax, legal or credit advice, execute transactions, manage assets, connect to bank accounts, or act as your financial adviser or fiduciary. Results depend on your inputs and simplified assumptions. They may omit taxes, fees, inflation, market changes and other circumstances. Forecasts and hypothetical returns are not promises, guarantees or recommendations. Verify important information and consult a qualified professional for decisions that require personal advice.</p>
	<p>Current subscription tiers, usage limits and student verification are demonstration features. Selecting them does not start a paid subscription or establish verified student status. Any future paid service will require separate, clearly disclosed pricing and acceptance before charges begin.</p>
	<h2>4. Local data and account recovery</h2>
	<p>Your financial profile is processed in your browser and can be saved in encrypted storage on your device using a separate local passcode. Creating an account does not upload, synchronize or back up this profile. Signing out does not erase device storage. Clearing browser data, losing the device or forgetting the local passcode may make the saved profile permanently unavailable. An account password reset cannot recover that passcode or decrypt the local profile. Use a trusted device and keep your own records.</p>
	<h2>5. Acceptable use</h2>
	<p>Do not use FinSight to violate laws or others’ rights, commit fraud, distribute malicious code, obtain unauthorized access, scrape private account data, bypass safeguards or usage controls, or interfere with service availability. Do not submit another person’s personal information without lawful authority. Security research must avoid accessing others’ data or disrupting service; report issues using our contact address.</p>
	<h2>6. Ownership and your information</h2>
	<p>You retain rights in information you provide. You authorize us and our service providers to process it only as needed to operate, protect and support the service as described in our <a href="/privacy">Privacy Policy</a>. FinSight’s branding and original service content belong to their respective owners. We permit personal use of the service under these Terms. Third-party and open-source components remain subject to their own licenses. You may not imply our endorsement or misuse our branding.</p>
	<h2>7. Availability, changes and termination</h2>
	<p>We may maintain, modify or discontinue features and may suspend access for material violations, security risks or legal requirements. Where reasonably practicable and lawful, we will explain restrictions and provide an opportunity to resolve them. You can stop using FinSight at any time and request account deletion through our contact address. Deleting an account does not remove browser data from your devices. We will give reasonable notice of material service changes affecting existing accounts when practicable.</p>
	<h2>8. Disclaimers and liability</h2>
	<p>To the extent permitted by applicable law, the service is provided "as is" and "as available", without a warranty that it will be uninterrupted, error-free, secure against every threat or suitable for a particular purpose. We do not guarantee any financial outcome. To the extent permitted by law, we are not liable for indirect or consequential losses, lost profits or investment losses resulting from reliance on hypothetical outputs.</p>
	<p>Nothing in these Terms excludes or limits liability that cannot lawfully be excluded or limited, including liability for fraud, intentional misconduct, gross negligence where protected by law, or death or personal injury caused by negligence. Nothing removes mandatory consumer guarantees, remedies, privacy rights or other non-waivable protections. Any limitation applies only to the extent lawful and reasonable in your circumstances.</p>
	<h2>9. Disputes and applicable law</h2>
	<p>Please contact us first so we can try to resolve concerns informally; this is not a condition on exercising your legal rights. Subject to mandatory law, the law of {legal.jurisdiction || '[operator jurisdiction]'} governs these Terms. If you are a consumer, mandatory protections and any right to bring proceedings in your place of residence remain available. These Terms do not require arbitration or waive class actions or jury trials.</p>
	<h2>10. Updates and general provisions</h2>
	<p>We will publish updated Terms with a version date and give notice of material changes affecting accounts. When required, we will ask you to accept revised Terms before continuing the affected service. Changes do not retroactively remove accrued rights. If a provision is unenforceable, the remaining provisions continue to apply. A failure to enforce a provision does not waive it. These Terms and any separately accepted terms for a specific feature constitute the agreement for that feature.</p>
</LegalPage>
